language: python

python:
  - "3.5"
  - "3.4"
  - "2.7"

service:
  - postgresql

before_install:
  - export APP_SETTINGS="project.server.config.TestingConfig"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database flask_jwt_auth_testing;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade

script:
  - python manage.py cov

after_success:
  coveralls
